### ISSUE TITLE
Official nugget package.

### ISSUE THREAD

**Issue by quico14** [subor/nng.NETCore#47]
Is this the official nugget package?
https://www.nuget.org/packages/Subor.nng.NETCore/1.1.1

I ask because I cannot find there some classes you have here.

Thanks.

**Comment by jake-ruyi** [comment]
Yes, that's it. It should be the same as what's in the `master` branch. What seems to be missing?

**Comment by quico14** [comment]
I am trying to do kind of this https://nanomsg.org/gettingstarted/pipeline.html but with your library and I can not find any thing to create a socket.

I can see lot of interfaces, but not classes to create the socket.

Thanks.

**Comment by jake-ruyi** [comment]
There's examples in the `tests/` folder like [this](https://github.com/subor/nng.NETCore/blob/master/tests/ReqRepTests.cs).
That factory takes care of loading the correct native library and is created as shown in the README:
```csharp
var path = Path.GetDirectoryName(typeof(Program).Assembly.Location);
var ctx = new nng.NngLoadContext(path);
var factory = nng.NngLoadContext.Init(ctx);
```

I should probably put together a demo showing how to get at the low-level API in [`nng.NetCore/Native/`](https://github.com/subor/nng.NETCore/tree/master/nng.NETCore/Native).

**Comment by jake-ruyi** [comment]
I should also mention that example was for nanomsg while this library is for the very similar but different "nng". Here's the nng [getting started](https://nanomsg.org/gettingstarted/nng/index.html) docs.

**Comment by quico14** [comment]
Thanks a lot!
